services:
  # Development service
  comparative-genomics-service-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "8000:8000"
    environment:
      DB_USER: coge
      DB_PASSWORD: dummy_password
      DB_NAME: comparative_genomics
      DB_HOST: db
      DB_PORT: 5432
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin123
      MINIO_BUCKET_NAME: genomes
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy
    profiles:
      - dev
  comparative-genomics-service-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "8001:8000"
      
    environment:
      DB_USER: coge
      DB_PASSWORD: dummy_password
      DB_NAME: comparative_genomics
      DB_HOST: db
      DB_PORT: 5432
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin123
      MINIO_BUCKET_NAME: genomes
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy
    profiles:
      - prod
  db:
    image: postgres:15
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: coge
      POSTGRES_PASSWORD: dummy_password
      PGDATA: /data/postgres
      POSTGRES_DB: comparative_genomics
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - db:/data/postgres

  minio:
    image: minio/minio:latest
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - minio_data:/data

volumes:
  db:
  minio_data:
