from enum import Enum


class ImportMode(str, Enum):
    CREATE_ORGANISM = "CREATE_ORGANISM"
    ADD_GENOME = "ADD_GENOME"


class ImportStatus(str, Enum):
    QUEUED = "QUEUED"
    VALIDATING_FASTA = "VALIDATING_FASTA"
    PROCESSING_FASTA = "PROCESSING_FASTA"
    VALIDATING_GFF3 = "VALIDATING_GFF3"
    PROCESSING_GFF3 = "PROCESSING_GFF3"
    PUBLISHING = "PUBLISHING"
    PUBLISHED = "PUBLISHED"
    ACTION_REQUIRED = "ACTION_REQUIRED"
    FAILED_RETRYABLE = "FAILED_RETRYABLE"
    CANCELLED = "CANCELLED"


ACTIVE_IMPORT_STATUSES = (
    ImportStatus.QUEUED.value,
    ImportStatus.VALIDATING_FASTA.value,
    ImportStatus.PROCESSING_FASTA.value,
    ImportStatus.VALIDATING_GFF3.value,
    ImportStatus.PROCESSING_GFF3.value,
    ImportStatus.PUBLISHING.value,
    ImportStatus.ACTION_REQUIRED.value,
    ImportStatus.FAILED_RETRYABLE.value
)


class ImportComponent(str, Enum):
    FASTA = "FASTA"
    GFF3 = "GFF3"
    INFRASTRUCTURE = "INFRASTRUCTURE"
    PUBLICATION = "PUBLICATION"


class ImportExecutionType(str, Enum):
    FASTA_VALIDATION = "FASTA_VALIDATION"
    FASTA_PROCESSING = "FASTA_PROCESSING"
    GFF3_VALIDATION = "GFF3_VALIDATION"
    GFF3_PROCESSING = "GFF3_PROCESSING"
